app:
  env: dev
  name: polaris-oj
mysql:
  MYSQL_DB_NAME: "polaris-oj"
  MYSQL_DB_PASSWORD: "ALin0915="
jwt:
  validTime: 60
  key: "polaris-oj"
session:
  SESSION_PAIRKEY: "polaris-oj-backend"
log:
  LogPath: "./polaris_logger"
  LogContextKey: "user"