// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/get/user/login": {
            "get": {
                "tags": [
                    "用户"
                ],
                "summary": "获取当前登录用户",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user_vo.UserVO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/question/add": {
            "post": {
                "tags": [
                    "问题"
                ],
                "summary": "问题添加",
                "parameters": [
                    {
                        "description": "add question info",
                        "name": "addInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/question_dto.QuestionAddRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponse-bool"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/question/delete": {
            "post": {
                "tags": [
                    "问题"
                ],
                "summary": "问题删除",
                "parameters": [
                    {
                        "description": "delete question info",
                        "name": "deleteInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponse-bool"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/question/get": {
            "get": {
                "tags": [
                    "问题"
                ],
                "summary": "通过问题的Identity获取问题详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "identity",
                        "name": "Identity",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponse-question_vo_QuestionVO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/question/question_submit/do": {
            "post": {
                "tags": [
                    "问题提交"
                ],
                "summary": "添加问题提交记录",
                "parameters": [
                    {
                        "description": "add questionSubmit info",
                        "name": "addInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/questionsubmit_dto.QuestionSubmitAddRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponse-bool"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/question/question_submit/list/page": {
            "post": {
                "tags": [
                    "问题提交"
                ],
                "summary": "分页查询提交问题",
                "parameters": [
                    {
                        "description": "query questionSubmit info",
                        "name": "queryInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/questionsubmit_dto.QuestionSubmitQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponse-array_questionsubmit_vo_QuestionSubmitVO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/question/update": {
            "post": {
                "tags": [
                    "问题"
                ],
                "summary": "问题修改",
                "parameters": [
                    {
                        "description": "update question info",
                        "name": "updateInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/question_dto.QuestionUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponse-bool"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/user/delete": {
            "post": {
                "tags": [
                    "用户"
                ],
                "summary": "用户删除",
                "parameters": [
                    {
                        "description": "delete question info",
                        "name": "deleteInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponse-bool"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/user/login": {
            "post": {
                "tags": [
                    "用户"
                ],
                "summary": "用户登陆",
                "parameters": [
                    {
                        "description": "user login infos",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user_dto.UserLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponse-user_vo_UserVO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/user/logout": {
            "post": {
                "tags": [
                    "用户"
                ],
                "summary": "用户退出登录",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponse-bool"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/user/my": {
            "post": {
                "tags": [
                    "用户"
                ],
                "summary": "用户更新自己的数据",
                "parameters": [
                    {
                        "description": "user login infos",
                        "name": "updateInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user_dto.UserUpdateMyUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponse-bool"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/user/register": {
            "post": {
                "tags": [
                    "用户"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "user Register infos",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user_dto.UserAddRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponse-bool"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.DeleteRequest": {
            "type": "object",
            "required": [
                "identity"
            ],
            "properties": {
                "identity": {
                    "type": "string"
                }
            }
        },
        "judgecase.JudgeCase": {
            "type": "object",
            "properties": {
                "input": {
                    "type": "string"
                },
                "output": {
                    "type": "string"
                }
            }
        },
        "judgeconfig.JudgeConfig": {
            "type": "object",
            "properties": {
                "memoryLimit": {
                    "type": "integer"
                },
                "stackLimit": {
                    "type": "integer"
                },
                "timeLimit": {
                    "type": "integer"
                }
            }
        },
        "question_dto.QuestionAddRequest": {
            "type": "object",
            "required": [
                "answer",
                "content",
                "judgeCase",
                "judgeConfig",
                "title"
            ],
            "properties": {
                "answer": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "identity": {
                    "type": "string"
                },
                "judgeCase": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/judgecase.JudgeCase"
                    }
                },
                "judgeConfig": {
                    "$ref": "#/definitions/judgeconfig.JudgeConfig"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "question_dto.QuestionUpdateRequest": {
            "type": "object",
            "required": [
                "answer",
                "content",
                "identity",
                "judgeCase",
                "judgeConfig",
                "tags",
                "title"
            ],
            "properties": {
                "answer": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "identity": {
                    "type": "string"
                },
                "judgeCase": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/judgecase.JudgeCase"
                    }
                },
                "judgeConfig": {
                    "$ref": "#/definitions/judgeconfig.JudgeConfig"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "question_vo.QuestionVO": {
            "type": "object",
            "properties": {
                "acceptedNum": {
                    "description": "题目通过数",
                    "type": "integer"
                },
                "content": {
                    "description": "内容",
                    "type": "string"
                },
                "createTime": {
                    "description": "TODO question: 这边时间的名字没有对应上，不知道会不会出问题",
                    "type": "string"
                },
                "favourNum": {
                    "description": "收藏数",
                    "type": "integer"
                },
                "identity": {
                    "description": "id",
                    "type": "string"
                },
                "judgeConfig": {
                    "description": "判题配置（json 对象）",
                    "allOf": [
                        {
                            "$ref": "#/definitions/judgeconfig.JudgeConfig"
                        }
                    ]
                },
                "submitNum": {
                    "description": "题目提交数",
                    "type": "integer"
                },
                "tags": {
                    "description": "标签列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "thumbNum": {
                    "description": "点赞数",
                    "type": "integer"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                },
                "updateTime": {
                    "description": "更新时间",
                    "type": "string"
                },
                "userId": {
                    "description": "创建用户 id",
                    "type": "integer"
                },
                "userVO": {
                    "description": "创建题目人的信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/user_vo.UserVO"
                        }
                    ]
                }
            }
        },
        "questionsubmit_dto.QuestionSubmitAddRequest": {
            "type": "object",
            "required": [
                "language",
                "questionId"
            ],
            "properties": {
                "conetnt": {
                    "description": "Status     int32  ` + "`" + `json:\"status\"` + "`" + `                              // 提交状态",
                    "type": "string"
                },
                "language": {
                    "description": "编程语言",
                    "type": "string"
                },
                "questionId": {
                    "description": "问题的identity",
                    "type": "string"
                }
            }
        },
        "questionsubmit_dto.QuestionSubmitQueryRequest": {
            "type": "object",
            "properties": {
                "current": {
                    "type": "integer"
                },
                "language": {
                    "type": "string"
                },
                "pageSize": {
                    "type": "integer"
                },
                "questionId": {
                    "type": "string"
                },
                "sortField": {
                    "type": "string"
                },
                "sortOrder": {
                    "type": "string"
                },
                "status": {
                    "description": "可以由以下类别来查询",
                    "type": "integer"
                },
                "userId": {
                    "description": "管理员查询的是否可以用UserID来查询",
                    "type": "string"
                }
            }
        },
        "questionsubmit_vo.QuestionSubmitVO": {
            "type": "object",
            "properties": {
                "conetnt": {
                    "description": "用户代码",
                    "type": "string"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "identity": {
                    "description": "唯一ID",
                    "type": "string"
                },
                "judgeInfo": {
                    "description": "判题信息（json 对象）",
                    "type": "string"
                },
                "language": {
                    "description": "编程语言",
                    "type": "string"
                },
                "question": {
                    "description": "题目信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/question_vo.QuestionVO"
                        }
                    ]
                },
                "questionId": {
                    "description": "题目 id",
                    "type": "string"
                },
                "status": {
                    "description": "判题状态（0 - 待判题、1 - 判题中、2 - 成功、3 - 失败）",
                    "type": "integer"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                },
                "user": {
                    "description": "提交用户信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/user_vo.UserVO"
                        }
                    ]
                },
                "userId": {
                    "description": "题目创建用户唯一ID",
                    "type": "string"
                }
            }
        },
        "user_dto.UserAddRequest": {
            "type": "object",
            "required": [
                "checkPassword",
                "userAccount",
                "userPassword"
            ],
            "properties": {
                "checkPassword": {
                    "type": "string"
                },
                "userAccount": {
                    "type": "string"
                },
                "userPassword": {
                    "type": "string"
                }
            }
        },
        "user_dto.UserLoginRequest": {
            "type": "object",
            "required": [
                "userAccount",
                "userPassword"
            ],
            "properties": {
                "userAccount": {
                    "description": "Identity     string ` + "`" + `json:\"identity,omitempty\"` + "`" + `",
                    "type": "string"
                },
                "userPassword": {
                    "type": "string"
                }
            }
        },
        "user_dto.UserUpdateMyUserRequest": {
            "type": "object",
            "properties": {
                "userAvatar": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "userProfile": {
                    "type": "string"
                }
            }
        },
        "user_vo.UserVO": {
            "type": "object",
            "properties": {
                "createTime": {
                    "type": "string"
                },
                "identity": {
                    "type": "string"
                },
                "updateTime": {
                    "type": "string"
                },
                "userAvatar": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "userProfile": {
                    "type": "string"
                },
                "userRole": {
                    "type": "string"
                }
            }
        },
        "vo.BaseResponse-array_questionsubmit_vo_QuestionSubmitVO": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应码",
                    "type": "integer"
                },
                "data": {
                    "description": "接口，表示具体信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/questionsubmit_vo.QuestionSubmitVO"
                    }
                },
                "message": {
                    "description": "请求结果[发生错误则是错误信息，如果没有错误则是SUCCESS.Code的值]",
                    "type": "string"
                }
            }
        },
        "vo.BaseResponse-bool": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应码",
                    "type": "integer"
                },
                "data": {
                    "description": "接口，表示具体信息",
                    "type": "boolean"
                },
                "message": {
                    "description": "请求结果[发生错误则是错误信息，如果没有错误则是SUCCESS.Code的值]",
                    "type": "string"
                }
            }
        },
        "vo.BaseResponse-question_vo_QuestionVO": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应码",
                    "type": "integer"
                },
                "data": {
                    "description": "接口，表示具体信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/question_vo.QuestionVO"
                        }
                    ]
                },
                "message": {
                    "description": "请求结果[发生错误则是错误信息，如果没有错误则是SUCCESS.Code的值]",
                    "type": "string"
                }
            }
        },
        "vo.BaseResponse-user_vo_UserVO": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应码",
                    "type": "integer"
                },
                "data": {
                    "description": "接口，表示具体信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/user_vo.UserVO"
                        }
                    ]
                },
                "message": {
                    "description": "请求结果[发生错误则是错误信息，如果没有错误则是SUCCESS.Code的值]",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
